// <auto-generated />
namespace WebApplication4.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addedentityidfornotification : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedentityidfornotification));
        
        string IMigrationMetadata.Id
        {
            get { return "201805151056261_'added entity id for notification'"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
