// <auto-generated />
namespace WebApplication4.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Removedphotoandphotolikesmodels : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Removedphotoandphotolikesmodels));
        
        string IMigrationMetadata.Id
        {
            get { return "201803301909578_removed photo and photolikes models"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
